name: "Oblaka 3D"
picture: "assets/img/picture.jpg"
bio: "3D Printing studio"
meta:
  lang: "en"
  description: "3D printing studio Oblaka"
  title: "Oblaka 3D"
  author: "Oblaka 3D"
  siteUrl: "https://oblaka3d.github.io"
links:
  - name: "Telegram"
    url: "https://t.me/oblaka3d"
  - name: "Instagram"
    url: "https://instagram.com/oblaka_3d"
  - name: "Github"
    url: "https://github.com/oblaka3d"
  - name: "Обратная связь / Feedback"
    url: "https://forms.yandex.ru/cloud/676f359d4936394123539a57/"
  - name: "Google table with parts"
    url: "https://docs.google.com/spreadsheets/d/1uaw4e5GOIojs754IB9Zk6cMgyAjc2cfumn-E2qBvigM/edit?usp=sharing"
  # - name: "Магазин"
  #   url: ""
  # - name: "OZON"
  #   url: ""
theme: "custom"

